name: docs

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: "Configure git"
        run: |
          git config user.name "CICD"
          git config user.email "cicd@github.com"

      - name: "Install dependencies"
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry install

      - name: "Build mkdocs"
        run: make doc-deploy
