name: docs

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: "Configure git"
        run: |
          git config user.name "CICD"
          git config user.email "cicd@github.com"

      - name: "Build mkdocs"
        run: make doc-deploy
