name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  format:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Format checking with Ruff Format
        run: make format

  lint:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Lint with Ruff
        run: make lint-python

      - name: Lint with Sqlfluff
        run: make lint-sql

  type-check:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Type checking with Mypy
        run: make type

  test:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Test with pytest
        run: make test

  build:
    needs:
      - setup
    runs-on: ubuntu-latest
    steps:
      - name: Verify build
        run: make build

  # nox:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version:
  #         - "3.9"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install dependencies
  #       run: |
  #         make init-uv
  #         make install

  #     - name: Test with nox
  #       run: make test-all
