name: tests

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry install

      - name: Format checking with Ruff Format
        run: poetry run ruff format --check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry install

      - name: Lint with Ruff
        run: poetry run ruff --output-format=github .

      - name: Lint with Sqlfluff
        run: poetry run sqlfluff lint .

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry install

      - name: Type checking with Mypy
        run: poetry run mypy .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
          poetry install

      - name: Test with pytest
        run: poetry run coverage run -m pytest -vv tests && poetry run coverage report

  # nox:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       python-version:
  #         - "3.9"
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install dependencies
  #       run: |
  #         curl -sSL https://install.python-poetry.org | python3 - --version 1.6.1
  #         poetry install

  #     - name: Test with nox
  #       run: poetry run nox --reuse-existing-virtualenvs --no-install
